Raise min tested rustc version to 1.34
Required by use of str::split_ascii_whitespace in the cc crate.

    error[E0658]: use of unstable library feature 'split_ascii_whitespace' (see issue #48656)
        --> .cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.62/src/lib.rs:2157:14
         |
    2157 |             .split_ascii_whitespace()
         |              ^^^^^^^^^^^^^^^^^^^^^^